server:
  port: 5001
spring:
  application:
    name: microservce-user-consumer-5001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: microservce-user-consumer-5001
    app-group-name: true
    prefer-ip-address: true