spring:
  profiles:
    active: -dev
---
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka9001:9001/eureka/,http://eureka9002:9002/eureka/,http://eureka9003:9003/eureka/ #集群版
info:
  app.name: 微服务-用户服务提供者
  company.name: www.neusoft.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
spring:
  profiles: dev
  zipkin:
    base-url: http://localhost:8001/
    enabled: true
  sleuth:
    enabled: true
    sampler:
      probability: 1 #采样率，值为[0,1]之间的任意实数，顾名思义，这里代表100%采集报告。
  application:
    #微服务名称
    name: microservicecloud-user
  datasource:
    druid:
      url: jdbc:oracle:thin:@192.168.159.133:1521/orcl
      #      url: jdbc:oracle:thin:@127.0.0.1:1521/xe
      #      url: jdbc:oracle:thin:@192.168.100.205:1521/chm
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: cxdc
      password: neusoft
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-wait: 60
      pool-prepared-statements: true
      max-open-prepared-statements: 10
      validation-query: select 1 from  dual
      validation-query-timeout: 600
      min-evictable-idle-time-millis: 60000
      keep-alive: true
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      filters: stat,wall

