spring:
  profiles:
    active: -dev
---
server:
  port: 9002
spring:
  profiles: dev
eureka:
  instance:
    #hostname: localhost   #eureka服务端实例名称
    hostname: eureka9002   #eureka服务端实例名称 集群版 修改host文件
  client:
    register-with-eureka: true #表示不向服务注册中心注册自己
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    # 单机版 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka9001:9001/eureka/,http://eureka9003:9003/eureka/



